name: Java Maven CI 

on:
  push:
    branches:
      - main
      - develop

    
  pull_request:
    branches:
      - main
      - develop

permissions: 
  contents: read

jobs:
  build-and-test:
    name: Build and Test 
    runs-on: ubuntu-latest

    steps: 
      #checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      #Install Java
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven 

      #Verify maven installation 
      - name: verify Maven
        run: mvn -version 

      #Download dependencies
      - name: Resolve dependencies
        run: mvn dependency:resolve

      # Compile source code
      - name: Compile Project
        run: mvn clean compile 

      #Execute unit tests
      - name: Run Unit tests
        run: mvn test 

      # Package application
      - name: Package Application 
        run: mvn package -DskipTests 

      #Upload test reports 
      - name: Upload Test reports 
        if: always() 
        uses: actions/upload-artifact@v4 
        with: 
          name: test-reports 
          path: target-surefire-reports/

      # Upload JAR/WAR artifacts
      - name: Upload artifacts 
        uses: actions/upload-artifact@v4 
        with: 
          name: application-build
          path: |
            target/*.jar
            target/*.war 

      

























